
global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

rule_files:
- "/etc/prometheus/rules.yml"

alerting:
  alertmanagers:
  - timeout: "10s"
    api_version: v2
    path_prefix: /
    scheme: http
    follow_redirects: true

    static_configs:
    - targets:
      - "localhost:9093"


scrape_configs:
- job_name: "my_localhost_1"
  static_configs:
  - targets:
    - "localhost:8001"
    labels:
      env: develop
  metrics_path: /metrics
  honor_labels: false
  honor_timestamps: true
  scheme: http
  follow_redirects: true
  body_size_limit: 0
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

- job_name: "my_localhost_2"
  static_configs:
  - targets:
    - "localhost:8002"
    labels:
      env: qa

  metrics_path: /metrics
  honor_labels: false
  honor_timestamps: true
  scheme: http
  follow_redirects: true
  body_size_limit: 0
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

