version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: "prometheus_dummy_server"
    network_mode: host
    volumes:
      - ./../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./../config/prometheus/rules.yml:/etc/prometheus/rules.yml

  graphana:
    image: grafana/grafana-oss
    container_name: "grafana"
    network_mode: host
    expose:
      - 3000

  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    network_mode: host
    expose:
      - 9093
    volumes:
     - ./../config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  alert_receiver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app_alert_receiver"
    command: uvicorn main:app --port 5001 --reload
    network_mode: host
    volumes:
      - ./../src/api_receiver:/opt/my_project

  client1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app_client_1"
    command: uvicorn main:app --port 8001 --reload
    network_mode: host
    volumes:
      - ./../src/api_client:/opt/my_project

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --port 8002 --reload
    container_name: "app_client_2"
    network_mode: host
    volumes:
      - ./../src/api_client:/opt/my_project
